name: Deploy to Render.com

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Render.com CLI
        uses: render-com/cli-action@v1
        with:
          render-token: ${{ secrets.RENDER_TOKEN }}

      - name: Deploy to Render.com
        run: |
          render deploy -- --branch=main 
