name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Display SoftUni username
        run: echo "Shadowz"

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.15.0'  
      - name: Install dependencies
        run: npm install
        working-directory: library

      - name: Run unit tests
        run: npm run test:unit
        
        
  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install
        working-directory: Shadowz-regular-exam/library

      - name: Run tests
        run: npm run test:ui
        working-directory: Shadowz-regular-exam/library

  merge:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Merge to main branch
        if: success() && github.event_name == 'pull_request'
        run: |
          git fetch origin main
          git checkout main
          git merge --no-ff ${{ github.event.pull_request.head.sha }}
          git push origin main
